const plotDataRaw = [
    {
        "plot_no": "1",
        "plot_size": "303",
        "facing": "North-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "2",
        "plot_size": "222",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "3",
        "plot_size": "222",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "4",
        "plot_size": "223",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "5",
        "plot_size": "223",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "6",
        "plot_size": "227",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "7",
        "plot_size": "189",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "8",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "9",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "10",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "11",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "12",
        "plot_size": "250",
        "facing": "North-West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "13",
        "plot_size": "275",
        "facing": "North-East",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "14",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "15",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "16",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "17",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "18",
        "plot_size": "210",
        "facing": "East",
        "plot_status": "HOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-",
        "customer_name": "",
        "reference_name": ""
    },
    {
        "plot_no": "19",
        "plot_size": "175",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "20",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "21",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "22",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "23",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "24",
        "plot_size": "225",
        "facing": "North-West",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "25",
        "plot_size": "327",
        "facing": "East",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "26",
        "plot_size": "312",
        "facing": "East",
        "plot_status": "HOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "27",
        "plot_size": "325",
        "facing": "East",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "28",
        "plot_size": "354",
        "facing": "East",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "29",
        "plot_size": "384",
        "facing": "East",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "30",
        "plot_size": "287",
        "facing": "North",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "31",
        "plot_size": "260",
        "facing": "North-East",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "32",
        "plot_size": "302",
        "facing": "South-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "33",
        "plot_size": "221",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "34",
        "plot_size": "221",
        "facing": "East",
        "plot_status": "HOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "35",
        "plot_size": "221",
        "facing": "East",
        "plot_status": "SOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "36",
        "plot_size": "221",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "37",
        "plot_size": "221",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "38",
        "plot_size": "300",
        "facing": "North-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "39",
        "plot_size": "250",
        "facing": "North-West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "40",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "41",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "42",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "43",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "44",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "45",
        "plot_size": "250",
        "facing": "South-West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "46",
        "plot_size": "275",
        "facing": "South-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "47",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "48",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "49",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "50",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "51",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "52",
        "plot_size": "275",
        "facing": "North-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "53",
        "plot_size": "225",
        "facing": "South-West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "54",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "55",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "56",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "57",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "58",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "59",
        "plot_size": "225",
        "facing": "North-West",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "60",
        "plot_size": "333",
        "facing": "South-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "61",
        "plot_size": "278",
        "facing": "South",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "62",
        "plot_size": "183",
        "facing": "South",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "63",
        "plot_size": "306",
        "facing": "South",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "64",
        "plot_size": "223",
        "facing": "South",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "65",
        "plot_size": "222",
        "facing": "North",
        "plot_status": "MORTGAGE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "66",
        "plot_size": "306",
        "facing": "North",
        "plot_status": "AVAILABLE",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "67",
        "plot_size": "183",
        "facing": "North",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "68",
        "plot_size": "278",
        "facing": "North",
        "plot_status": "AVAILABLE",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "69",
        "plot_size": "333",
        "facing": "North-East",
        "plot_status": "HOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "70",
        "plot_size": "298",
        "facing": "South-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "71",
        "plot_size": "218",
        "facing": "East",
        "plot_status": "SOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "72",
        "plot_size": "218",
        "facing": "East",
        "plot_status": "SOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "73",
        "plot_size": "218",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "74",
        "plot_size": "218",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "75",
        "plot_size": "218",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "76",
        "plot_size": "339",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "77",
        "plot_size": "254",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "78",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "79",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "80",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "81",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "82",
        "plot_size": "183",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "83",
        "plot_size": "250",
        "facing": "South-West",
        "plot_status": "SOLD",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "84",
        "plot_size": "275",
        "facing": "South-East",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "85",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "SOLD",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "86",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "87",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "88",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "89",
        "plot_size": "202",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "90",
        "plot_size": "223",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "91",
        "plot_size": "294",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "92",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "93",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "94",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "95",
        "plot_size": "165",
        "facing": "West",
        "plot_status": "REGISTERED",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "96",
        "plot_size": "216",
        "facing": "South-West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    }
];
